package com.example.alva.analytics;

public enum HyperlinkIssue implements Issue {
    TEXTUAL_HYPERLINK_TO_ABSOLUTE_URI_CONVERSION_FAILED, TEXTUAL_HYPERLINK_TO_ABSOLUTE_URI_CONVERSION_SKIPPED,
    TEXTUAL_HYPERLINK_CANNOT_BE_PARSED, DISCARDING_FRAGMENT_FAILED, URI_TO_URL_CONVERSION_FAILED,
    URI_DELIVERS_NO_HTML_CONTENT
}
